version: '3.5'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-test}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #  - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    # networks:
      # - postgres
    restart: unless-stopped
    # restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/postgres
